#!/bin/sh
# Build the arXiv upload tarball from the paper root.
#
# The payload is derived from main.fls, so it contains exactly the files
# pdflatex actually read on the last build, plus main.tex, main.bbl and the
# .bst. Everything else in this directory -- rebuttal records, revision plans,
# notes/, drafts/, the nested .git, and the 13 MB of unused figures -- is
# excluded by construction rather than by an ignore list that can go stale.
#
# Run `latexmk -pdf main.tex` first: a stale main.fls yields a stale payload.
# arXiv does not run BibTeX, so main.bbl must ship and must be current.

set -eu

cd "$(dirname "$0")"
out=${1:-arxiv.tar.gz}

[ -f main.fls ] || { echo "main.fls missing -- run latexmk -pdf main.tex first" >&2; exit 1; }
[ -f main.bbl ] || { echo "main.bbl missing -- arXiv does not run BibTeX" >&2; exit 1; }

list=$(mktemp)
trap 'rm -f "$list"' EXIT

# INPUT lines with a ./ prefix are the local files; main.aux and main.out are
# regenerated by arXiv and would only go stale in the tarball.
LC_ALL=C grep -a '^INPUT \./' main.fls \
  | sed 's|^INPUT \./||' \
  | LC_ALL=C grep -av '^main\.\(aux\|out\)$' \
  | sort -u > "$list"
printf 'main.tex\nacl_natbib.bst\n' >> "$list"
sort -u "$list" -o "$list"

missing=0
while read -r f; do
  [ -f "$f" ] || { echo "missing input: $f" >&2; missing=1; }
done < "$list"
[ "$missing" -eq 0 ] || exit 1

# Exactly one \documentclass must reach arXiv, or AutoTeX picks the wrong root.
texfiles=$(LC_ALL=C grep -a '\.tex$' "$list")
roots=$(LC_ALL=C grep -al '\\documentclass' $texfiles | wc -l | tr -d ' ')
[ "$roots" -eq 1 ] || { echo "expected 1 \\documentclass in payload, found $roots" >&2; exit 1; }

# The preprint switches must both be set, or the upload is anonymised.
LC_ALL=C grep -q '\\usepackage\[preprint\]{acl}' main.tex \
  || { echo "main.tex is not in preprint mode" >&2; exit 1; }
LC_ALL=C grep -q '^\\preprintmodetrue' style/preamble.tex \
  || { echo "style/preamble.tex is not in preprint mode" >&2; exit 1; }

tar czf "$out" -T "$list"

# Report the real byte count, not du's block allocation -- arXiv's 50 MB cap
# applies to the file, and du rounds up enough to mislead.
bytes=$(wc -c < "$out" | tr -d ' ')
echo "$out  $(wc -l < "$list" | tr -d ' ') files  $bytes bytes"
[ "$bytes" -lt 52428800 ] || echo "WARNING: exceeds arXiv's 50 MB limit" >&2
